version: '3'
services:
  catchbot:
    ports:
      - "7654:7654"
    environment:
      - CATCHBOT_CERT=/certs/cert.pem
      - CATCHBOT_KEY=/certs/key.pem
      - CATCHBOT_HOST=0.0.0.0
      - CATCHBOT_PORT=7654

